name: Fetch FreeFire Stats

on:
  workflow_dispatch:
    inputs:
      uid:
        description: 'Free Fire UID'
        required: true
        type: string

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
           python app.py
           curl -X GET 'http://127.0.0.1:3000/api/account?uid=1673824281&region=ind'
        
